
[catalogue]

	[catalogue.r]
	known_missing  = [81000, 82000]
	#src = http://libgen.rs/repository_torrent/
	#dir = "data/torrent/r"

	[catalogue.fiction]
	known_missing  = []
	#srv = http://libgen.rs/ficton/repository_torrent/
	#dir = "data/torrent/fiction"

[peersearch]
	udp_batchsize = 60
