name: Commit date to master
on: push
jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
#        #with:
#          poetry-version: ${{ matrix.poetry-version }}
      - name: make env - run poetry install
        run: make env

      - name: run main programm
        run: make mgmt

      - name: git st
        run: git status



#      - name: save current date
#        run: |
#          date > time.txt
#
#      - name: setup git config
#        run: |
#          git config user.name "GitHub Actions Bot"
#          git config user.email "<foo@bar.com>"
#
#      - name: commit
#        run: |
#          echo cool
#          echo git add time.txt
#          echo git commit -m "new date commit"
#          echo git push origin master
